version: 2.1

executors:
  serverless-base-image:
    docker:
      - image: vuvuzella/docker-serverless-base-image:0.1.6
        # auth:
        #   username: $DOCKERHUB_USERNAME
        #   password: $DOCKERHUB_PASSWORD
    working_directory: /root/project

orbs:
  browser-tools: circleci/browser-tools@1.1.0
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  Package_App:
    executor: serverless-base-image
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Build Application
          command: |
            ./run build
      - save_cache:
          key: api_dependencies-v1-{{ .Branch }}-{{ checksum "backend/api/app/package-lock.json" }}
          paths:
            - backend/api/app/node_modules
      - persist_to_workspace:
          root: /root/project
          paths:
            - backend/api/artifacts

  Unit_Test:
    executor: serverless-base-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - api_dependencies-v1-{{ .Branch }}-{{ checksum "backend/api/app/package-lock.json" }}
      - run:
          name: Unit Test
          command: |
            ./run test_unit

  Integration_Test:
    executor: serverless-base-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - api_dependencies-v1-{{ .Branch }}-{{ checksum "backend/api/app/package-lock.json" }}
      - run:
          name: Integration Test
          command: |
            ./run test_integration

  System_Test:
    executor: serverless-base-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - api_dependencies-{{ .Branch }}-{{ checksum "backend/api/app/package-lock.json" }}
      - run:
          name: Integration Test
          command: |
            echo "Running System Test"
            echo "Job not yet supported"

  Deploy_App_Dev:
    executor: serverless-base-image
    environment:
      ENVIRONMENT: dev
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: ap-southeast-2
          profile-name: admin-dev
      - attach_workspace:
          at: /root/project
      - run:
          name: Deploy Application to DEV
          command: |
            echo 'Deploying Serverless App to DEV'
            ./run deploy

  Deploy_App_Staging:
    executor: serverless-base-image
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Deploy Application to STAGING
          command: |
            echo 'Deploying Serverless App to Staging'
            echo "Job not yet supported"

  Deploy_App_Prod:
    executor: serverless-base-image
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Deploy Application to PROD
          command: |
            echo 'Deploying Serverless App to Prod'
            echo "Job not yet supported"

workflows:
  Example_Workflow:
    jobs:
      - Package_App

      # Run Unit Test and Integration Test concurrently
      - Unit_Test:
          requires:
            - Package_App

      - Deploy_App_Dev:
          requires:
            - Unit_Test

      # For serverless/infrastructure testing, Parallelization of Integration Test might not be possible
      # because of the need to deploy infra first before running tests
      - Integration_Test:
          requires:
            - Deploy_App_Dev

      - Hold_Dev:
          type: approval
          requires:
            - Integration_Test

      - Deploy_App_Staging:
          requires:
          - Hold_Dev

      - System_Test:
          requires:
          - Deploy_App_Staging

      - Hold_Staging:
          type: approval
          requires:
            - System_Test

      - Deploy_App_Prod:
          requires:
            - Hold_Staging
