version: 2.1

executors:
  base_image:
    docker:
      - image: cimg/base:stable
  custom_image:
    docker:
      - image: vuvuzella/docker-serverless:0.1.1
  custom_image_auth:
    docker:
      - image: vuvuzella/docker-serverless:0.1.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

orbs:
  browser-tools: circleci/browser-tools@1.1.0
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  Install_Build_Dep:
    docker:
      - image: vuvuzella/docker-serverless-base-image:0.1.5
    steps:
      - checkout
      - run:
          name: Check setup environment
          command: |
            echo 'in Install_Build_Dep'
            terraform -version
            terragrunt -version
            ls -a

  Package_App:
    docker:
      - image: vuvuzella/docker-serverless-base-image:0.1.5
    steps:
      - run:
          name: Build Application
          command: |
            echo 'in Package_App'
            terraform -version
            terragrunt -version
            ls -a

  Unit_Test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Unit Test
          command: |
            echo 'Running Unit Tests'
            echo 'Second line'

  Integration_Test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Integration Test
          command: |
            echo 'Running Integration Tests'
            echo 'Second line'

  Deploy_App:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Deploy Application to AWS
          command: |
            echo 'Deploying Serverless App to AWS'

workflows:
  Example_Workflow:
    jobs:
      - Install_Build_Dep

      # Run Unit Test and Integration Test concurrently
      - Unit_Test:
          requires:
            - Install_Build_Dep

      # For serverless/infrastructure testing, Parallelization of Integration Test might not be possible
      # because of the need to deploy infra first before running tests
      - Integration_Test:
          requires:
            - Install_Build_Dep

      # - Hold_For_Approval:
      #     type: approval
      #     requires:
      #       - Integration_Test
      #       - Unit_Test

      # - Package_App:
      #     requires:
      #       - Hold_For_Approval

      # - Deploy_App:
      #     requires:
      #       - Package_App
