version: 2.1

executors:
  serverless-base-image:
    docker:
      - image: vuvuzella/docker-serverless-base-image:0.1.6
        # auth:
        #   username: $DOCKERHUB_USERNAME
        #   password: $DOCKERHUB_PASSWORD
    working_directory: /root/project

orbs:
  browser-tools: circleci/browser-tools@1.1.0
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  Install_Build_Dep:
    executor: serverless-base-image
    steps:
      - checkout
      - run:
          name: Install Build Dependencies
          command: |
            cd app
            npm install
      - save_cache:
          key: app_dependencies-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
          paths:
            - app/node_modules

  Package_App:
    executor: serverless-base-image
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - restore_cache:
          keys:
            - app_dependencies-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
            # - app_dependencies-
      - run:
          name: Build Application
          command: |
            ./run clean
            ./run build
      - persist_to_workspace:
          root: /root/project
          paths:
            - artifacts

  Unit_Test:
    executor: serverless-base-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - app_dependencies-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
      - run:
          name: Unit Test
          command: |
            pushd app
            npm run test:unit

  Integration_Test:
    executor: serverless-base-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - app_dependencies-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
      - run:
          name: Integration Test
          command: |
            pushd app
            npm run test:integration

  System_Test:
    executor: serverless-base-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - app_dependencies-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
      - run:
          name: Integration Test
          command: |
            pushd app
            echo "Running System Test"

  Deploy_App_Dev:
    executor: serverless-base-image
    environment:
      ENVIRONMENT: dev
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Deploy Application to DEV
          command: |
            echo 'Deploying Serverless App to DEV'
            ls -a

  Deploy_App_Staging:
    executor: serverless-base-image
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Deploy Application to STAGING
          command: |
            echo 'Deploying Serverless App to Staging'
            ls -a

  Deploy_App_Prod:
    executor: serverless-base-image
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Deploy Application to PROD
          command: |
            echo 'Deploying Serverless App to Prod'
            ls -a

workflows:
  Example_Workflow:
    jobs:
      - Install_Build_Dep

      # Run Unit Test and Integration Test concurrently
      - Unit_Test:
          requires:
            - Install_Build_Dep

      - Package_App:
          requires:
            - Install_Build_Dep

      - Deploy_App_Dev:
          requires:
            - Package_App

      # For serverless/infrastructure testing, Parallelization of Integration Test might not be possible
      # because of the need to deploy infra first before running tests
      - Integration_Test:
          requires:
            - Deploy_App_Dev

      - Hold_Dev:
          type: approval
          requires:
            - Integration_Test

      - Deploy_App_Staging:
          requires:
          - Hold_Dev

      - System_Test:
          requires:
          - Deploy_App_Staging

      - Hold_Staging:
          type: approval
          requires:
            - System_Test

      - Deploy_App_Prod:
          requires:
            - Hold_Staging
