version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  aws-cli: circleci/aws-cli@2.1.0
jobs:
  Get_Code:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code has arrived
          command: |
            ls -a
            echo "Code has arrived"

  Package_App:
    docker:
      - image: cimg/node:17.2-browsers
    steps:
      - browser-tools/install-browser-tools
      - run:
          name: Build Application
          command: |
            node -v

  Unit_Test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Unit Test
          command: |
            echo 'Running Unit Tests'
            echo 'Second line'

  Integration_Test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Integration Test
          command: |
            echo 'Running Integration Tests'
            echo 'Second line'

  Deploy_App:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Deploy Application to AWS
          command: |
            echo 'Deploying Serverless App to AWS'

workflows:
  Example_Workflow:
    jobs:
      - Get_Code

      # Run Unit Test and Integration Test concurrently
      - Unit_Test:
          requires:
            - Get_Code

      # For serverless/infrastructure testing, Parallelization of Integration Test might not be possible
      # because of the need to deploy infra first before running tests
      - Integration_Test:
          requires:
            - Get_Code

      - Hold_For_Approval:
          type: approval
          requires:
            - Integration_Test
            - Unit_Test

      - Package_App:
          requires:
            - Hold_For_Approval

      - Deploy_App:
          requires:
            - Package_App
