version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  aws-cli: circleci/aws-cli@2.1.0
jobs:
  Install_Build_Dep:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Setup Build Environment
          command: |
            mkdir build-dep &&
            cd build-dep &&
            curl -L https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_linux_amd64.zip -o terraform.zip &&
            unzip -x -o terraform.zip &&
            mv ./terraform /usr/local/bin/terraform &&
            terraform -version &&
            cd ..
            ls -a &&
            cd build-dep &&
            curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.1/terragrunt_linux_amd64 -o terragrunt &&
            chmod u+x ./terragrunt &&
            mv ./terragrunt /usr/local/bin/terragrunt &&
            terragrunt -version &&
            cd ..

  Package_App:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Build Application
          command: |
            ./run clean
            ./run build
            ls -a && ls ./artifacts

  Unit_Test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Unit Test
          command: |
            echo 'Running Unit Tests'
            echo 'Second line'

  Integration_Test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Integration Test
          command: |
            echo 'Running Integration Tests'
            echo 'Second line'

  Deploy_App:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Deploy Application to AWS
          command: |
            echo 'Deploying Serverless App to AWS'

workflows:
  Example_Workflow:
    jobs:
      - Install_Build_Dep

      # Run Unit Test and Integration Test concurrently
      - Unit_Test:
          requires:
            - Install_Build_Dep

      # For serverless/infrastructure testing, Parallelization of Integration Test might not be possible
      # because of the need to deploy infra first before running tests
      - Integration_Test:
          requires:
            - Install_Build_Dep

      - Hold_For_Approval:
          type: approval
          requires:
            - Integration_Test
            - Unit_Test

      - Package_App:
          requires:
            - Hold_For_Approval

      - Deploy_App:
          requires:
            - Package_App
