version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  aws-cli: circleci/aws-cli@2.1.0
jobs:
  build:
    docker:
      # - image: alpine:3.7
      - image: cimg/node:17.2-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Unit Test
          command: |
            echo 'Running Unit Tests'
            echo 'Second line'
      - run:
          name: Integration Test
          command: |
            echo 'Running Integration Tests'
            echo 'Second line'
      - run:
          name: Code has arrived
          command: |
            ls -a
            echo "Code has arrived"
      - run:
          name: Running in a unique container
          command: |
            node -v
  # build:
  #   docker:
  #     - image: alpine:3.7
  #   steps:
  #     - run:
  #         name: Package Application
  #         command: |
  #           echo 'Packing Application'
  # deploy:
  #   docker:
  #     - image: alpine:3.7
  #   steps:
  #     - run:
  #         name: Deploying Application
  #         command: |
  #             echo 'Deploying Application'
