version: 2.1
jobs:
  test:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Unit Test
          command: |
            echo 'Running Unit Tests'
            echo 'Second line'
      - run:
          name: Integration Test
          command: |
            echo 'Running Integration Tests'
            echo 'Second line'
      - run:
          name: Code has arrived
          command: |
            ls -a
            echo "Code has arrived"
  # build:
  #   docker:
  #     - image: alpine:3.7
  #   steps:
  #     - run:
  #         name: Package Application
  #         command: |
  #           echo 'Packing Application'
  # deploy:
  #   docker:
  #     - image: alpine:3.7
  #   steps:
  #     - run:
  #         name: Deploying Application
  #         command: |
  #             echo 'Deploying Application'
