#! /bin/env bash

#
# Message to display the usage and help
#
function usage {
    local txt=(
"Build script for serverless applications"
"Usage: $SCRIPT [options] <command> [arguments]"
""
"Commands:"
"  build             Build the application code"
"  test              Run the application tests"
"  deploy            Deploy the the application to cloud"
""
"Options:"
"  --help, -h        Print help"
"  --version, -v     Print version"

    )
    printf "%s\n" "${txt[@]}"
}

#
# Message to display if the tool is incorrectly used
#
function badusage {
    local message="$1"
    local txt=(
"For an overview of the command, execute:"
"$SCRIPT --help"
    )

    [[ $message ]] && printf "$message\n"

    printf "%s\n" "${txt[@]}"
}

#
# Builds the application code and creates build artifacts
#
function app-build {
  npm run clean
  npm install
  npm run build

  zip -r dependencies.zip ./node_modules
  pushd dist
  zip -r ../app.zip ./ -x node_modules
  popd

  printf "%s\n" "${txt[@]}"
}

#
# Tests the application code
#
function app-test_unit {
#     local txt=(
# "Running tests with params: $*"
#     )
#     printf "%s\n" "${txt[@]}"
  npm run test:unit
}

function app-test_integration {
  npm run test:integration
}

#
# Deploys the application
#
function app-deploy {
    local txt=(
"Deploying application with params: $*"
    )
    printf "%s\n" "${txt[@]}"
}

#
# Process options
#
while(( $# ))
do
    case "$1" in

        --help | -h)
            usage
            exit 0
        ;;

        test_unit)
          command=$1
          shift
          app-$command $*
          exit 0
        ;;

        test_integration)
          command=$1
          shift
          app-$command $*
          exit 0
        ;;

        build)
            command=$1
            shift   # shifts positional arguments passed
            app-$command $* # call the command and pass in the remaining commands, the commands will be indexed from $1 from the perspective of the command
            exit 0
        ;;

        *)
            badusage "Option/Command not recognized"
            exit 1
        ;;
    # TODO: Add build, test and deploy, rollback? functions
    esac
done

badusage
exit 1
