version: 0.2

env:
  shell: bash
  # parameter-store:

  # secrets-manager:
    # Another way to get secret
  # exported-variables:
    # for next stage in codepipeline

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      # install OS packages
      - mkdir build-dep &&
        pushd build-dep &&
        curl -L https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_linux_amd64.zip -o terraform.zip &&
        unzip -x -o terraform.zip &&
        mv ./terraform /usr/local/bin/terraform &&
        terraform -version &&
        popd
      - ls -a &&
        pushd build-dep &&
        curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.1/terragrunt_linux_amd64 -o terragrunt &&
        chmod u+x ./terragrunt &&
        mv ./terragrunt /usr/local/bin/terragrunt &&
        terragrunt -version &&
        popd
    on-failure: ABORT

  pre_build:
    commands:
      - echo "Prebuild - executing commands"
      - exit 1
    on-failure: CONTINUE

  build:
    commands:
      - echo "Hello Codebuild" build phase
      - exit 0
    on-failure: ABORT
    finally:
      - echo "Build - This should always display"

  post_build:
    commands:
      - echo "Hello Codebuild post-build phase"
# artifacts:
#   files:
    # output directory of the output files
  